# Generated by Django 5.0.6 on 2025-05-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas', to='restaurantes.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platillos', to='restaurantes.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_barra', models.PositiveIntegerField()),
                ('capacidad', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barras', to='restaurantes.restaurante')),
            ],
            options={
                'unique_together': {('restaurante', 'numero_barra')},
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_mesa', models.PositiveIntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('capacidad', models.PositiveIntegerField(blank=True, default=4, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='restaurantes.restaurante')),
            ],
            options={
                'unique_together': {('restaurante', 'numero_mesa')},
            },
        ),
    ]
