services:
  - type: web
    name: app-personal-rest
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: uvicorn restaurante.asgi:application --host 0.0.0.0 --port $PORT

